### ISSUE TITLE
implement negate method on the chain

### ISSUE THREAD

**Issue by bruce-lindsay** [bruce-lindsay/expect-apex#19]
```apex
Expect.that(7).negated.shouldBeGreaterThan(7);
```

**Comment by jamessimone** [comment]
Would you consider the syntax: Expect.that(7).should.not.beGreaterThan(7)?

**Comment by bruce-lindsay** [comment]
I initially didn't want to because the extra periods look cluttered. However, it reads a lot better. What are your thoughts?

**Comment by jamessimone** [comment]
I'm torn. on the one hand, it reads better.  on the other, your point about the extra periods is definitely legitimate.  Depends on what we're going for!

**Comment by bruce-lindsay** [comment]
Also not is a reserved word https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_reserved_words.htm
